source "https://rubygems.org"

ruby "~> 3.2"

gem "sinatra", "~> 4.1"
gem "sinatra-contrib", "~> 4.1"
gem "puma", "~> 6.4"
gem "rackup", "~> 2.1"
gem "sqlite3", "~> 2.0"
gem "rqrcode", "~> 2.2"

group :test do
  gem "minitest", "~> 5.20"
  gem "rack-test", "~> 2.1"
  gem "webrick", "~> 1.8"
end
